### ISSUE TITLE
Mediasoup is 1.0.2 now

### ISSUE THREAD

**Issue by Globik** [mganeko/mediasoup_sample#1]
Any plan to update to mediasoup 1.0.2?

**Comment by mganeko** [comment]
Thanks for your interest. I'd like to update for madiasoup 1.x. Sorry, but It may take a few months.

**Comment by mganeko** [comment]
I updated the sample for mediasoup v1.1.
Please try it with most recent mediasoup.

**Comment by Globik** [comment]
Thank you so much. A very nice example with the mediasoup api.

**Comment by mganeko** [comment]
closed
