### ISSUE TITLE
HTTPS issued

### ISSUE THREAD

**Issue by yarekc** [mganeko/mediasoup_sample#2]
Hi,
Does not work on chrome since chrome needs HTTPS for wbertc.
**Do you have an update to support HTTPS ?**

**Comment by mganeko** [comment]
Thaks for you comment.

Currently, I do not have updates for HTTPS.
I you would like to use with HTTPS, then please
- prepare SSL certificate
- change express codes for using https
- change ws (websocket) codes for using ssl.

I would appreciate if you could share your experience.

**Comment by yarekc** [comment]
- prepare SSL certificate DONE
- change express codes for using https : DONE
- change ws (websocket) codes for using ssl : I have no idea on how to do that !

**Comment by mganeko** [comment]
Thank you for your trial.
Please let me check how to use ssl in websocket.

**Comment by mganeko** [comment]
I have not tried yet, but I found this example.
https://github.com/websockets/ws/blob/master/examples/ssl.js

**Comment by yarekc** [comment]
Thanks for your time and your availability : you did great job.
I am sorry to write to you here, but I could not find your email anywhere. I would like to hire (pay) your services to adapt this sample to socket.io and HTTPS (I think it will be a piece of cake for you): are you ok for freelance work ?
My email is yarekc[at]gmail.com

Regards

**Comment by mganeko** [comment]
Thanks for your high valuation for this sample.
Since this repo strongly depends on mediasoup, please donate to mediasoup instead of paying for me.
https://www.paypal.me/inakibazcastillo/100

I added some samples.
* WebSocket + SSL
* Socket.io
* Socket.io + SSL

Please use them under MIT License.

**Comment by yarekc** [comment]
Hi, 
thanks again for your help and kindness. I already did adapt it by myself and your sample works great. 

the last problem I have is: anytime a new user streams, all connected users receive automatically his stream: that means if we have 20 persons in a room, each user will receive automatically 19 streams.

Is there a way to start/stop  the stream I want to receive ?
like a **playStream(userid)** function when clicking on userid button ?

Can you give me some clues on how to achieve that ?
BTW, I would like to send you a little bonus by paypal, can you give me your paypal address ?

Regards

**Comment by mganeko** [comment]
Hi, thanks for confirming the new codes.

> that means if we have 20 persons in a room, each user will receive automatically 19 streams.

I understand the use case, but I am afraid that it is not possible with RTCPeerConnection object.
It may be possible using rtpSender.disable()/enable(), but it is beyond the scope of this sample and my knowledge.

**Comment by yarekc** [comment]
Yes: I read that: 
https://groups.google.com/forum/#!searchin/mediasoup/RtpSender|sort:relevance/mediasoup/SExQCdLn7zo/3azmCOw2DgAJ

and tried without success.

How can I convince you to help me on that specific project ? 
(I can pay or send you some french food or wine for your help ;) )

**Comment by mganeko** [comment]
Sorry,
I do not know how to control remote streams.
Since it is out of the scope of this issue, I close it.
