### ISSUE TITLE
v2 update ?

### ISSUE THREAD

**Issue by yarekc** [mganeko/mediasoup_sample#4]
Any update for mediasoup v2 ?

**Comment by mganeko** [comment]
Not yet, but I would like to follow v2.

**Comment by mganeko** [comment]
I am trying to use mediasoup v2, but it has big change.
I could not make it work with v2.
I think I have to make  new sample for v2.
I can not estimate how long does it take.
Sorry.

**Comment by mganeko** [comment]
To handle with mediasoup V2, please try another example by footniko.

https://github.com/footniko/mediasoup-sample

**Comment by mganeko** [comment]
Finally, I made a new sample for mediasoup V2.
Please refer https://github.com/mganeko/mediasoup_sample_v2

**Comment by mganeko** [comment]
Close. Please try https://github.com/mganeko/mediasoup_sample_v2
